name: app_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ^3.24.0
  
dependencies:
  flutter_localization: ^0.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_framework: ^1.4.0
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  country_flags: ^3.0.0
  iconly: ^1.0.1
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  expansion_widget: ^0.1.0
  syncfusion_flutter_charts: ^29.1.33
  go_router: ^14.2.7
  fl_chart: ^0.69.0
  collection: ^1.18.0
  flutter_layout_grid: ^2.0.7
  syncfusion_flutter_calendar: ^29.1.33
  intl: ^0.19.0
  intl_utils:
  feather_icons: ^1.2.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.2
  syncfusion_flutter_datagrid: ^29.1.33
  magicoon_icons: ^0.0.5
  flex_color_picker: ^3.5.1
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.9.0
  iconsax_plus: ^1.0.0
  syntax_highlight: ^0.4.0
  url_strategy: ^0.3.0
  pdf: ^3.11.1
  printing: ^5.13.0
  path_provider: ^2.1.4
  share_plus: ^10.1.2
  open_filex: ^4.5.0
  omni_datetime_picker: ^2.0.5
  flutter_dotenv: ^5.2.1

  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  image: ^4.5.3
  image_watermark: ^0.1.0

  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.0
  month_year_picker: ^0.4.0


  # Remote Packages
  appflowy_board:
    # path: ../appflowy-board/
    git:
      url: https://github.com/iamtoricool/appflowy-board.git
      ref: main

  # responsive_grid:
  #   git: 
  #     url: https://github.com/iamtoricool/ResponsiveGrid_Flutter.git
  #     ref: master

  http: ^1.2.2
  http_parser: ^4.0.2
  mime: ^2.0.0
#  http_platforms: ^1.0.5
  shared_preferences: ^2.3.3
  api_network:
    path: packages/api_network


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/widget_images/
    - assets/images/widget_images/banner_images/
    - assets/images/sidebar_icons/
    - assets/images/widget_images/dashboard_icon/
    - assets/images/widget_images/card_images/feature_card/
    - assets/images/widget_images/sm_icon/
    - assets/images/widget_images/authentication_images/
    - assets/images/widget_images/dashboard_overview_icon/
    - assets/images/widget_images/svg_icons/
    - assets/images/widget_images/not_found_images/
    - assets/app_icons/
    - assets/images/widget_images/dashboard_overview_icon/ecommerce_admin_icons/
    - assets/images/widget_images/dashboard_overview_icon/ecommerce_admin_icons/category_icons/
    - assets/images/widget_images/dashboard_overview_icon/influencer_admin_icons/
    - assets/images/widget_images/dashboard_overview_icon/news_admin_icons/
    # static images
    - assets/images/static_images/
    - assets/images/logo/
    - assets/images/static_images/avatars/placeholder_avatar/
    - assets/images/static_images/icons/crypto_icons/
    - .env

  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900

flutter_intl:
  enabled: true